### ISSUE TITLE
==> /usr/local/Cellar/ocrmypdf/5.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/ocrmypdf--Pillow-20170522-98091-ijx36n/Pillow-4.1.1

### ISSUE THREAD

**Issue by raje2411** [jbarlow83/homebrew-ocrmypdf#2]
==> /usr/local/Cellar/ocrmypdf/5.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/ocrmypdf--Pillow-20170522-98091-ijx36n/Pillow-4.1.1
Last 15 lines from /Users/rraman/Library/Logs/Homebrew/ocrmypdf/08.pip:
  Removing source in /private/tmp/pip-nle_5h_k-build
Command "/usr/local/Cellar/ocrmypdf/5.0.1/libexec/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-nle_5h_k-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9ykj5dr5-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/ocrmypdf/5.0.1/libexec/bin/../include/site/python3.6/Pillow" failed with error code 1 in /private/tmp/pip-nle_5h_k-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/5.0.1/libexec/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/ocrmypdf/5.0.1/libexec/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/Cellar/ocrmypdf/5.0.1/libexec/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/Cellar/ocrmypdf/5.0.1/libexec/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/local/Cellar/ocrmypdf/5.0.1/libexec/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/local/Cellar/ocrmypdf/5.0.1/libexec/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-nle_5h_k-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9ykj5dr5-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/ocrmypdf/5.0.1/libexec/bin/../include/site/python3.6/Pillow" failed with error code 1 in /private/tmp/pip-nle_5h_k-build/

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jbarlow83/homebrew-ocrmypdf/issues

**Comment by jbarlow83** [comment]
Same as #1.

Unfortunately this error message is quite obtuse and I can't reproduce it. I did make a change that I think could have fixed the issue. Please try again and let me know if you get any different results. Thanks!
