### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by nachopants** [jbarlow83/homebrew-ocrmypdf#5]
➜  ~  brew install ocrmypdf        

==> Installing ocrmypdf from jbarlow83/ocrmypdf
==> Downloading https://files.pythonhosted.org/packages/6d/c4/764d141f612a9cf323cba31164236fb9a499c1cd932309117e1218e72c8c/ocrmypdf-5.4.2.tar.gz
Already downloaded: /Users/nacho/Library/Caches/Homebrew/ocrmypdf-5.4.2.tar.gz
HOMEBREW_PROCESSOR:Intel
HOMEBREW_USER_AGENT:Homebrew/1.3.7 (Macintosh; Intel Mac OS X 10.13.2)
TERM_PROGRAM:Apple_Terminal
HOMEBREW_AUTO_UPDATE_CHECKED:1
HOMEBREW_COMMAND_DEPTH:1
HOMEBREW_LIBRARY:/usr/local/Homebrew/Library
SHELL:/bin/zsh
TERM:xterm-256color
HOMEBREW_OS_VERSION:macOS 10.13.2
HOMEBREW_REPOSITORY:/usr/local/Homebrew
Apple_PubSub_Socket_Render:/private/tmp/com.apple.launchd.AB2QybgqZv/Render
HOMEBREW_ENABLE_AUTO_UPDATE_MIGRATION:1
TERM_PROGRAM_VERSION:400
TERM_SESSION_ID:0A289934-09B0-4614-B5A9-F9566C9A59D4
HOMEBREW_RUBY_PATH:/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby
HOMEBREW_GIT_CONFIG_FILE:/usr/local/Homebrew/.git/config
ZSH:/Users/nacho/.oh-my-zsh
USER:nacho
SSH_AUTH_SOCK:/private/tmp/com.apple.launchd.59IGDCfdQu/Listeners
HOMEBREW_ANALYTICS_USER_UUID:7E92912A-397A-4C35-A0D3-5019D7A59771
PAGER:less
HOMEBREW_CACHE:/Users/nacho/Library/Caches/Homebrew
LSCOLORS:Gxfxcxdxbxegedabagacad
HOMEBREW_USER_AGENT_CURL:Homebrew/1.3.7 (Macintosh; Intel Mac OS X 10.13.2) curl/7.54.0
HOMEBREW_BREW_FILE:/usr/local/bin/brew
PWD:/Users/nacho
HOMEBREW_MACOS_VERSION:10.13.2
HOMEBREW_ANALYTICS_ID:UA-76679469-1
LANG:en_AU.UTF-8
XPC_FLAGS:0x0
HOMEBREW_PRODUCT:Homebrew
XPC_SERVICE_NAME:0
SHLVL:1
HOMEBREW_PREFIX:/usr/local
LESS:-R
LOGNAME:nacho
LC_CTYPE:en_AU.UTF-8
HOMEBREW_VERSION:1.3.7
HOMEBREW_CELLAR:/usr/local/Cellar
HOMEBREW_CURL:/usr/bin/curl
DISPLAY:/private/tmp/com.apple.launchd.JgjdMY8qPO/org.macosforge.xquartz:0
HOMEBREW_SYSTEM:Macintosh
__CF_USER_TEXT_ENCODING:0x1F5:0x0:0xF
HOMEBREW_ERROR_PIPE:/tmp/homebrew20171117-26457-pnq60n/socket
OBJC:clang
CC:clang
HOMEBREW_CC:clang
OBJCXX:clang++
CXX:clang++
HOMEBREW_CXX:clang++
MAKEFLAGS:-j8
PKG_CONFIG_PATH:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/leptonica/lib/pkgconfig:/usr/local/opt/tesseract/lib/pkgconfig:/usr/local/opt/little-cms2/lib/pkgconfig:/usr/local/opt/x264/lib/pkgconfig:/usr/local/opt/ffmpeg/lib/pkgconfig:/usr/local/opt/qpdf/lib/pkgconfig:/usr/local/opt/openjpeg/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/webp/lib/pkgconfig:/usr/local/opt/zlib/lib/pkgconfig:/usr/local/opt/python3/lib/pkgconfig
PKG_CONFIG_LIBDIR:/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13:/opt/X11/lib/pkgconfig:/opt/X11/share/pkgconfig
HOMEBREW_CCCFG:sa
HOMEBREW_OPTIMIZATION_LEVEL:Os
HOMEBREW_OPT:/usr/local/opt
HOMEBREW_TEMP:/tmp
HOMEBREW_OPTFLAGS:-march=native
HOMEBREW_ARCHFLAGS:
CMAKE_PREFIX_PATH:/usr/local/opt/libffi:/usr/local/opt/zlib:/usr/local
CMAKE_FRAMEWORK_PATH:/usr/local/opt/python3/Frameworks:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks
CMAKE_INCLUDE_PATH:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/apache2:/opt/X11/include:/opt/X11/include/freetype2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH:/opt/X11/lib:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
ACLOCAL_PATH:/usr/local/share/aclocal:/opt/X11/share/aclocal
HOMEBREW_ISYSTEM_PATHS:/usr/local/include:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/apache2:/opt/X11/include:/opt/X11/include/freetype2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
HOMEBREW_INCLUDE_PATHS:/usr/local/opt/zlib/include
HOMEBREW_LIBRARY_PATHS:/usr/local/opt/libffi/lib:/usr/local/opt/zlib/lib:/usr/local/lib:/opt/X11/lib:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
HOMEBREW_DEPENDENCIES:pkg-config,libffi,libpng,jpeg,libtiff,leptonica,tesseract,little-cms2,ghostscript,lame,x264,xvid,ffmpeg,unpaper,qpdf,openjpeg,freetype,jpeg,webp,zlib,python3
HOMEBREW_FORMULA_PREFIX:/usr/local/Cellar/ocrmypdf/5.4.2
HOMEBREW_SDKROOT:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
MACOSX_DEPLOYMENT_TARGET:10.13
SDKROOT:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
HOMEBREW_PREFER_CLT_PROXIES:1
TMPDIR:/tmp
TEMP:/tmp
TMP:/tmp
PATH:/usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/pkg-config/bin:/usr/local/opt/libpng/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/leptonica/bin:/usr/local/opt/tesseract/bin:/usr/local/opt/little-cms2/bin:/usr/local/opt/ghostscript/bin:/usr/local/opt/lame/bin:/usr/local/opt/x264/bin:/usr/local/opt/ffmpeg/bin:/usr/local/opt/unpaper/bin:/usr/local/opt/qpdf/bin:/usr/local/opt/openjpeg/bin:/usr/local/opt/freetype/bin:/usr/local/opt/webp/bin:/usr/local/opt/python3/bin:/opt/X11/bin:/usr/bin:/bin:/usr/sbin:/sbin
HOME:/private/tmp/ocrmypdf-20171117-26957-geq4ha/ocrmypdf-5.4.2/.brew_home
_JAVA_OPTIONS: -Duser.home=/Users/nacho/Library/Caches/Homebrew/java_cache
CURL_HOME:/Users/nacho
SETUPTOOLS_SCM_PRETEND_VERSION:v5.4.2
==> Downloading https://files.pythonhosted.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz
Already downloaded: /Users/nacho/Library/Caches/Homebrew/ocrmypdf--homebrew-virtualenv-15.1.0.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/ocrmypdf--homebrew-virtualenv-20171117-26957-nvhsyd/target --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/nacho/Library/Logs/Homebrew/ocrmypdf/01.python3:
python3
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/tmp/ocrmypdf--homebrew-virtualenv-20171117-26957-nvhsyd/target
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jbarlow83/homebrew-ocrmypdf/issues

**Comment by nachopants** [comment]
Resolved with 
curl -O https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
python3 -m pip install -U pip setuptools

**Comment by jbarlow83** [comment]
Homebrew installs setuptools by default so I don't know why it was missing. It could be that you ran `brew` from inside a virtual environment, which is not a good idea. Otherwise, beats me.
