### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools'

### ISSUE THREAD

**Issue by freddey** [jbarlow83/homebrew-ocrmypdf#7]
.$ brew install ocrmypdf
==> Installing ocrmypdf from jbarlow83/ocrmypdf
==> Downloading https://files.pythonhosted.org/packages/c2/69/d250b73cab334a07608715db2f41bbf3d1e69e3f097042baec5cbf
Already downloaded: /Users/friedemann/Library/Caches/Homebrew/ocrmypdf-5.5.tar.gz
==> Downloading https://files.pythonhosted.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30c
Already downloaded: /Users/friedemann/Library/Caches/Homebrew/ocrmypdf--homebrew-virtualenv-15.1.0.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/ocrmypdf--homebrew-virtualenv-20180119-19656
Last 15 lines from /Users/friedemann/Library/Logs/Homebrew/ocrmypdf/01.python3:
python3
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/tmp/ocrmypdf--homebrew-virtualenv-20180119-19656-dxedss/target
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jbarlow83/homebrew-ocrmypdf/issues

**Comment by jbarlow83** [comment]
Same as issue #6

**Comment by freddey** [comment]
I had  the same mistake what helped:
1. Deinstall python and python 3
 brew remove python // brew remove python3
2. Neuinstallation von python 3
 brew install python3
4. install ocrmypdf
brew install ocrmypdf

And it work!
Greets Fred
